import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';
export const styles = StyleSheet.create({
  app: { flex: 1 },
  topSafeArea: { backgroundColor: COLORS.navy },
  landing: { flex: 1, backgroundColor: COLORS.navy },
  landingTop: { minHeight: 56, paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  logo: { fontSize: 23, fontWeight: '900', color: COLORS.primary, letterSpacing: -0.5 },
  logoHub: { color: COLORS.yellow },
  yellowPill: { backgroundColor: COLORS.yellow, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 999 },
  yellowPillText: { color: COLORS.primary, fontWeight: '800' },
  hero: { flex: 1, padding: 22, justifyContent: 'center' },
  badge: { flexDirection: 'row', alignItems: 'center', gap: 7, borderWidth: 1, borderColor: '#25334A', backgroundColor: '#0C1728', paddingHorizontal: 11, paddingVertical: 9, borderRadius: 999, alignSelf: 'flex-start' },
  badgeText: { color: '#D6DFEC', fontSize: 12 },
  heroTitle: { color: '#fff', fontSize: 40, lineHeight: 43, fontWeight: '900', marginTop: 24, letterSpacing: -1.4 },
  heroText: { color: '#A8B2C2', fontSize: 15, lineHeight: 23, marginTop: 18, marginBottom: 18 },
  dots: { flexDirection: 'row', gap: 7, marginBottom: 20 },
  dot: { width: 7, height: 7, borderRadius: 99, backgroundColor: '#344054' },
  dotActive: { width: 28, backgroundColor: COLORS.yellow },
  button: { minHeight: 48, borderRadius: 14, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 14, marginVertical: 5, flexDirection: 'row', gap: 8 },
  buttonText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  buttonSecondary: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#D8DDE6' },
  buttonSecondaryText: { color: COLORS.text },
  buttonDanger: { backgroundColor: COLORS.danger },
  ghostButton: { borderWidth: 1, borderColor: '#2A374B', padding: 14, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: 7, flexDirection: 'row', gap: 8 },
  ghostButtonText: { color: '#fff', fontWeight: '700' },
  authSafe: { flex: 1, backgroundColor: COLORS.navy },
  authScroll: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 20, paddingVertical: 14 },
  authTop: { minHeight: 52, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  pillDark: { borderWidth: 1, borderColor: '#26344A', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 5 },
  pillDarkText: { color: '#AAB5C4', fontSize: 12 },
  authCard: { backgroundColor: '#fff', borderRadius: 28, padding: 22, gap: 10 },
  authFooter: { color: '#667085', textAlign: 'center', fontSize: 10, marginTop: 14 },
  authTitle: { fontSize: 22, fontWeight: '900', color: COLORS.text, textAlign: 'center' },
  centerMuted: { color: COLORS.muted, textAlign: 'center', fontSize: 13, lineHeight: 20 },
  fieldWrap: { marginTop: 5 },
  fieldLabel: { color: COLORS.muted, fontSize: 11, fontWeight: '800', marginBottom: 6, textTransform: 'uppercase' },
  inputShell: { minHeight: 46, borderWidth: 1, borderColor: '#D8DDE6', backgroundColor: '#fff', borderRadius: 13, flexDirection: 'row', alignItems: 'center' },
  inputBare: { flex: 1, minHeight: 46, paddingHorizontal: 12, color: COLORS.text, fontSize: 14 },
  inputSimple: { minHeight: 46, borderWidth: 1, borderColor: '#D8DDE6', backgroundColor: '#fff', borderRadius: 13, paddingHorizontal: 13, color: COLORS.text, fontSize: 14, marginBottom: 4 },
  textarea: { minHeight: 110, textAlignVertical: 'top', paddingTop: 12 },
  linkRight: { color: COLORS.primary, textAlign: 'right', fontWeight: '700', fontSize: 12 },
  link: { color: COLORS.primary, fontWeight: '800' },
  largeIconCircle: { width: 64, height: 64, borderRadius: 32, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', backgroundColor: '#EFF3FF', marginVertical: 4 },
  header: { height: 56, backgroundColor: COLORS.navy, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: '#19263A' },
  headerIcon: { width: 38, height: 38, borderWidth: 1, borderColor: '#26344A', borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  headerAvatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: COLORS.primary, borderWidth: 2, borderColor: COLORS.yellow, alignItems: 'center', justifyContent: 'center' },
  headerAvatarText: { color: '#fff', fontWeight: '900' },
  content: { padding: 16 },
  pageTitle: { fontSize: 26, fontWeight: '900', color: COLORS.text },
  muted: { color: COLORS.muted, fontSize: 13, lineHeight: 20 },
  tinyMuted: { color: '#7B8495', fontSize: 10, lineHeight: 16 },
  card: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: COLORS.border, padding: 14 },
  cardHeading: { color: COLORS.text, fontWeight: '800', fontSize: 14 },
  searchWrap: { minHeight: 46, borderWidth: 1, borderColor: '#D8DDE6', backgroundColor: '#fff', borderRadius: 13, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 9 },
  searchInput: { flex: 1, minHeight: 44, color: COLORS.text, fontSize: 14 },
  tab: { paddingHorizontal: 16, paddingVertical: 10, borderWidth: 1, borderColor: '#D8DDE6', borderRadius: 12, backgroundColor: '#fff', marginRight: 8 },
  tabActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  tabText: { color: COLORS.text, fontWeight: '700' },
  tabTextActive: { color: '#fff' },
  postRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#EDF0F4' },
  avatarSmall: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#EDF0F4', alignItems: 'center', justifyContent: 'center' },
  avatarTiny: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#EDF0F4', alignItems: 'center', justifyContent: 'center' },
  skeletonWide: { height: 7, borderRadius: 99, width: '70%', backgroundColor: '#E7EBF0', marginBottom: 5 },
  commentRow: { flexDirection: 'row', gap: 8, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#EDF0F4' },
  commentMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  inlineIcon: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  commentInputRow: { flexDirection: 'row', gap: 8, alignItems: 'center', paddingTop: 10 },
  send: { width: 38, height: 38, borderRadius: 19, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  cameraBox: { aspectRatio: 4/3, borderRadius: 18, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  cameraText: { color: '#fff', marginTop: 14, fontWeight: '700' },
  recDot: { position: 'absolute', top: 14, right: 14, width: 10, height: 10, borderRadius: 5, backgroundColor: '#EF4444' },
  row: { flexDirection: 'row', gap: 8, alignItems: 'center', marginTop: 10 },
  squareButton: { minHeight: 48, minWidth: 76, backgroundColor: '#fff', borderWidth: 1, borderColor: '#D8DDE6', borderRadius: 14, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10, gap: 2 },
  squareButtonText: { fontSize: 10, color: COLORS.text, fontWeight: '700' },
  resultText: { color: COLORS.text, fontSize: 16, lineHeight: 23, fontWeight: '600' },
  uploadBox: { minHeight: 220, borderWidth: 2, borderStyle: 'dashed', borderColor: '#CBD2DC', borderRadius: 18, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', padding: 22, gap: 8 },
  fileIcons: { flexDirection: 'row', gap: 12 },
  historyRow: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 13, backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, marginBottom: 9 },
  historyIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#EFF3FF', alignItems: 'center', justifyContent: 'center' },
  deleteIcon: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  faq: { paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#EDF0F4' },
  success: { color: '#15803D', fontWeight: '800' },
  sentWrap: { alignItems: 'center', gap: 8, paddingVertical: 25 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  avatarLarge: { width: 68, height: 68, borderRadius: 34, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  avatarLargeText: { color: '#fff', fontSize: 25, fontWeight: '900' },
  profileName: { color: COLORS.text, fontSize: 21, fontWeight: '900', marginTop: 9 },
  stats: { flexDirection: 'row', marginVertical: 18 },
  statValue: { color: COLORS.primary, fontSize: 21, fontWeight: '900' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  infoBox: { borderWidth: 1, borderColor: '#D8DDE6', backgroundColor: '#F8FAFC', borderRadius: 12, padding: 12, color: COLORS.text, marginBottom: 12 },
  dangerCard: { marginTop: 12, borderRadius: 16, borderWidth: 2, borderColor: '#EFB4B4', backgroundColor: '#FFF5F5', padding: 14 },
  dangerText: { color: '#B42318', fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  sectionLabel: { color: COLORS.muted, fontSize: 11, fontWeight: '900', marginBottom: 8 },
  settingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#EDF0F4' },
  option: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 2, borderColor: COLORS.border, borderRadius: 13, padding: 13, marginTop: 8 },
  optionActive: { borderColor: COLORS.primary, backgroundColor: '#F2F5FF' },
  radio: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: '#AAB3C0', alignItems: 'center', justifyContent: 'center' },
  radioActive: { borderColor: COLORS.primary },
  radioInner: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.primary },
  preview: { backgroundColor: '#FFF8D6', borderWidth: 1, borderColor: '#F3D969', borderRadius: 16, padding: 14, marginTop: 12 },
  bottomNav: { position: 'absolute', left: 10, right: 10, height: 72, flexDirection: 'row', backgroundColor: COLORS.navy, borderRadius: 22, padding: 6, borderWidth: 1, borderColor: '#223046' },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 17, gap: 3 },
  navItemActive: { backgroundColor: COLORS.yellow },
  navLabel: { color: '#A8B2C2', fontSize: 9, fontWeight: '800' },
  navLabelActive: { color: COLORS.primary },
  menuOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.48)', zIndex: 90 },
  menu: { position: 'absolute', top: 0, left: 0, bottom: 0, width: '82%', backgroundColor: COLORS.navy, zIndex: 100, paddingHorizontal: 20, elevation: 20 },
  menuSubtitle: { color: '#7F8B9D', fontSize: 12, lineHeight: 18, marginTop: 12, marginBottom: 18 },
  menuItem: { paddingHorizontal: 10, paddingVertical: 9, borderRadius: 14, marginBottom: 5, flexDirection: 'row', alignItems: 'center', gap: 10 },
  menuItemActive: { backgroundColor: COLORS.yellow },
  menuIconBox: { width: 32, height: 32, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.06)', alignItems: 'center', justifyContent: 'center' },
  menuIconBoxActive: { backgroundColor: 'rgba(16,42,113,0.10)' },
  menuItemText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  menuItemTextActive: { color: COLORS.primary },
});

